<a href="https://colab.research.google.com/github/Diogo-code/Data-Mining-Diogo/blob/main/Midterm_Virtual_Part.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np
from sklearn import linear_model as lm
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

data = pd.read_csv('/content/irisdata - irisdata.csv')
data['sepal_length'] = data['sepal_length'].str.replace('$','')
data['sepal_width'] = data['sepal_width'].str.replace('%','')
data['petal_length'] = data['petal_length'].str.replace(',','')
data['petal_width'] = data['petal_width'].str.replace('t','')

data['sepal_length'] = data['sepal_length'].astype('float')
data['sepal_width'] = data['sepal_width'].astype('float')
data['petal_length'] = data['petal_length'].astype('float')
data['petal_width'] = data['petal_width'].astype('float')
data['species'] = data['species'].astype('str')
data.set_index('ID', inplace= True)

targetFeature = 'species'
dataFeature = data.drop(targetFeature, axis=1)

MostImportantVariable = data.std().sort_values(ascending=False)[0:1]
SecondImportantVariable = data.std().sort_values(ascending=False)[0:2]



xb = np.array(data['petal_length'])
xb = xb.reshape(-1,1)
yb = np.array(data['species'])
yb = yb.reshape(-1,1)


xb = np.array(data['sepal_width'])
xb = xb.reshape(-1,1)
yb = np.array(data['species'])
yb = yb.reshape(-1,1)


BestDataModel = data[[targetFeature, MostImportantFeature.index[0]]]
BestDataModel

            species  petal_length
ID
0.501578     setosa        1400.0
0.952522     setosa        1400.0
0.178990     setosa        1300.0
0.768478     setosa        1500.0
0.046327     setosa        1400.0
...             ...           ...
0.591577  Virginica        5200.0
0.241802  virginica        5000.0
0.932065  virginica        5200.0
0.582025  Virginica        5400.0
0.462726  virginica        5100.0

[150 rows x 2 columns]